image: atlassian/default-image:2

pipelines:
  custom:
    QA_PLATFORM_TEST_AUTOMATION:
      - variables: #list variable names under here
          - name: SUITE_NAME
          - name: ENVIRONMENT
          - name: SUBJECT
          - name: PROJECT
            default: NON-PCI
      - step:
          name: TAF
          services:
            - docker
          script: # Modify the commands below to build your repository.
            - APP_NAME=platform-test-automation
            - Team=platform
            - sed -i "s+SUITE_NAME+$SUITE_NAME+g" start_command.sh
            - DIR=`date +%d-%m-%y `-$BITBUCKET_BUILD_NUMBER
            - sed -i "s/BITBUCKCET_BUILD_NUMBER/$DIR/g" start_command.sh
            - sed -i "s/APP_NAME/$APP_NAME/g" start_command.sh
            - sed -i "s/ENV/$ENVIRONMENT/g" start_command.sh
            - sed -i "s/SUBJECT/$SUBJECT/g" start_command.sh
            - if [[ $ENVIRONMENT == "prod" || $ENVIRONMENT == "gcp" ]]; then sed -i "s/MAIL_ID/kiran.kumar@cleartrip.com,varalakshmi.venkateshaiah@cleartrip.com,saicharan.yadau@cleartrip.com,vrushabh.gurjar@cleartrip.com,ns.likhitha@cleartrip.com/g" start_command.sh ; elif [ $ENVIRONMENT == "qa" || $ENVIRONMENT == "qa-gcp" ]; then sed -i "s/MAIL_ID/kiran.kumar@cleartrip.com,varalakshmi.venkateshaiah@cleartrip.com,saicharan.yadau@cleartrip.com,vrushabh.gurjar@cleartrip.com,ns.likhitha@cleartrip.com/g" start_command.sh ; fi
            - git clone git@bitbucket.org:cleartrip/docker_dependency.git
            - mv docker_dependency/* .
            - docker login -u $DOCKERHUB_UN -p $DOCKERHUB_PW
            - docker build -t $DOCKER_REG_URL/$APP_NAME:$BITBUCKET_BUILD_NUMBER .
            - chmod +x $QA2_LOGIN
            - ./$QA2_LOGIN $APP_NAME
            - chmod +x $QA2_DEPLOY
            - if [[ $ENVIRONMENT == "qa" ]]; then Environment='DC' ./$QA2_DEPLOY $APP_NAME $Team; fi
            - if [[ $ENVIRONMENT == "qa-gcp" ]]; then Environment='GCP' ./$QA2_DEPLOY $APP_NAME $Team; fi